<?php
declare(strict_types=1);

/**
 * Generated by scripts/build_seo_runtime.py.
 * Source: data/seo/ownership-registry.json.
 * Do not edit this file directly.
 */

return array(
    'contract_version' => '1.0.0',
    'source' => array(
        'registry_version' => '2.0.0',
        'sha256' => 'a1c7c3dce4d45744df3e9edc358201ba398ad83a146c0581b1efdd3c20cdbd0a',
    ),
    'migration_gates' => array(
        '/5-טריקים-לטיסות-סופר-זולות-לתאילנד/' => array(
            'route_id' => 'route-cheap-flight-tips-legacy',
            'current_owner_id' => 'cheap-flight-tips-legacy',
            'candidate' => 'thailand-flights',
            'state' => 'evidence_pending',
            'release_blocked' => true,
            'indexing_policy' => 'index',
            'expected_redirect_target' => null,
        ),
        '/עסקים-בתאילנד/' => array(
            'route_id' => 'route-business-short-redirect',
            'current_owner_id' => 'business-in-thailand',
            'candidate' => 'business-in-thailand',
            'state' => 'target_review_pending',
            'release_blocked' => true,
            'indexing_policy' => 'redirect',
            'expected_redirect_target' => '/עסקים-בתאילנד-סקירה-כללית/',
        ),
    ),
);
